"""
Strategy 1.0 — Survivorship-bias-free backtest using the Tiingo dynamic universe.

Runs two backtests back-to-back and compares them:
  Run A (baseline) : close > $10,  ADV > $20M,  eligible_days ≥ 252  → 2,943 tickers
  Run B (sensitive) : close > $10,  ADV > $50M,  eligible_days ≥ 252  → 1,891 tickers

Universe is loaded from data/tiingo_eligible_universe.csv (generated by 08_eligible_universe.py).
Price data is read from the local Tiingo parquet cache (no API calls).

Usage:
    python src/scripts/09_run_v1_unbiased.py
    python src/scripts/09_run_v1_unbiased.py --run a   # only the $20M run
    python src/scripts/09_run_v1_unbiased.py --run b   # only the $50M run
"""

import argparse
import json
import logging
import os
import sys
import time
from dataclasses import replace
from pathlib import Path

_root = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_root / "src"))

_env = _root / ".env"
if _env.exists():
    for line in _env.read_text().splitlines():
        if "=" in line and not line.startswith("#"):
            k, _, v = line.partition("=")
            os.environ.setdefault(k.strip(), v.strip())

import pandas as pd

from data.adapters.tiingo import TiingoAdapter
from data.pipeline import load_price_panel
from indicators.precompute import precompute_indicators
from backtest.engine import BacktestEngine
from reports.baseline import generate_baseline_report
from strategy.params import StrategyParams
from strategy.v1.strategy_v1 import StrategyV1

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%H:%M:%S",
)
logger = logging.getLogger(__name__)

TIINGO_CACHE = _root / "data" / "cache" / "tiingo"
EU_CSV       = _root / "data" / "tiingo_eligible_universe.csv"

DEFAULT_START = "2004-01-02"   # matches Tiingo cache start (2004-01-01 is non-trading)
DEFAULT_END   = "2026-06-12"   # matches Tiingo cache end; avoids incremental API calls
MIN_ELIGIBLE_DAYS = 252

BASE_PARAMS = StrategyParams(
    min_price               = 10.0,
    min_market_cap_b        = 2.0,
    min_adv_m               = 20.0,   # overridden per run
    breakout_window         = 200,
    atr_period              = 20,
    stop_loss_multiplier    = 2.0,
    min_stop_distance_pct   = 0.005,
    trail_multiplier_r1     = 3.0,
    trail_multiplier_r3     = 3.0,
    trail_multiplier_r5     = 5.0,
    risk_per_trade          = 0.01,
    position_cap            = 0.05,
    heat_limit              = 0.10,
    correlation_window      = 60,
    correlation_threshold   = 0.70,
    correlation_reduction   = 0.50,
    volume_filter_multiplier = 1.5,
    breakout_strength_min   = 0.0,
    gap_filter              = 0.025,
    commission_bps          = 3.0,
    slippage_bps            = 10.0,
    cash_proxy              = "SHY",
    regime_filter_enabled   = True,
)


def load_dynamic_universe(min_adv_m: float) -> list[str]:
    """
    Return tickers from tiingo_eligible_universe.csv that satisfy:
      - eligible_days >= MIN_ELIGIBLE_DAYS  (≥ 1 year of ADV > $20M & close > $10)

    For the $50M sensitivity run, the daily ADV > $50M filter is applied by the
    engine on every trading day, so we load the superset (2,943 tickers) for
    both runs.  This is correct: the pre-filter ensures we don't load useless
    short-lived tickers; the engine's daily filter determines actual eligibility.
    """
    if not EU_CSV.exists():
        raise FileNotFoundError(f"Universe CSV not found: {EU_CSV}\n"
                                "Run: python src/scripts/08_eligible_universe.py")
    eu = pd.read_csv(EU_CSV)
    # Always load the ≥252-day ($20M) superset; the engine applies the daily ADV threshold.
    tickers = eu[eu["eligible_days"] >= MIN_ELIGIBLE_DAYS]["ticker"].tolist()
    logger.info("Dynamic universe (%d-day filter): %d tickers loaded from CSV",
                MIN_ELIGIBLE_DAYS, len(tickers))
    return sorted(tickers)


def run_backtest(
    label: str,
    adv_m: float,
    universe: list[str],
    panel: dict,
    indicators: dict,
    strategy_tickers: list[str],
    output_dir: Path,
    start: str,
    end: str,
    initial_capital: float,
) -> dict:
    """Run one backtest and return its metrics dict."""
    output_dir.mkdir(parents=True, exist_ok=True)

    params = replace(BASE_PARAMS, min_adv_m=adv_m)

    print(f"\n{'='*65}")
    print(f"  {label}")
    print(f"  Universe     : {len(universe):,} tickers loaded")
    print(f"  Strategy pool: {len(strategy_tickers):,} tickers")
    print(f"  ADV 门槛     : ${adv_m:.0f}M (daily filter)")
    print(f"  Period       : {start} → {end}")
    print(f"  Output       : {output_dir}")
    print(f"{'='*65}\n")

    t1 = time.time()
    logger.info("Running backtest …")
    strategy = StrategyV1(params)
    engine   = BacktestEngine(
        strategy=strategy,
        price_panel=panel,
        indicators=indicators,
        params=params,
        initial_capital=initial_capital,
    )
    results = engine.run(start, end, strategy_tickers)
    logger.info(
        "Backtest done in %.1fs  (%d trading days, %d trades)",
        time.time() - t1, len(results.daily_nav), len(results.trade_log),
    )

    spy_raw = panel.get("SPY")
    generate_baseline_report(results, spy_raw, output_dir)

    m = results.compute_metrics()
    print(f"\n{results.summary()}")
    return m


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", choices=["a", "b", "both"], default="both",
                    help="a=$20M run, b=$50M run, both=run both (default)")
    ap.add_argument("--start",           default=DEFAULT_START)
    ap.add_argument("--end",             default=DEFAULT_END)
    ap.add_argument("--initial-capital", default=10_000_000, type=float)
    args = ap.parse_args()

    token = os.environ.get("TIINGO_API_TOKEN", "")
    if not token:
        logger.error("TIINGO_API_TOKEN not set in .env")
        sys.exit(1)

    t_total = time.time()

    # ── Load universe (superset for both runs) ────────────────────────────────
    universe = load_dynamic_universe(min_adv_m=20.0)   # 2,943 tickers

    # Always add auxiliary tickers
    auxiliary = {BASE_PARAMS.cash_proxy, "SPY", BASE_PARAMS.regime_ticker}
    load_list = sorted(set(universe) | auxiliary)

    # ── Load price panel once (shared by both runs) ───────────────────────────
    adapter = TiingoAdapter(api_token=token)
    logger.info("Loading price panel (%d tickers) …", len(load_list))
    t_load = time.time()
    panel = load_price_panel(
        load_list, adapter,
        start=args.start, end=args.end,
        cache_dir=TIINGO_CACHE,
    )
    logger.info("Loaded %d tickers in %.1fs", len(panel), time.time() - t_load)

    # ── Precompute indicators once (shared by both runs) ─────────────────────
    # Indicators depend only on breakout_window and atr_period (same in both runs).
    # The ADV threshold (min_adv_m) is applied by the engine daily, not here.
    auxiliary        = {BASE_PARAMS.cash_proxy, "SPY", BASE_PARAMS.regime_ticker}
    strategy_tickers = [t for t in universe if t in panel and t not in auxiliary]
    logger.info("Strategy pool: %d tickers", len(strategy_tickers))

    t_ind = time.time()
    logger.info("Precomputing indicators (once, shared by both runs) …")
    indicators = precompute_indicators(
        {t: panel[t] for t in strategy_tickers}, BASE_PARAMS
    )
    logger.info("Indicators ready in %.1fs", time.time() - t_ind)

    results_a = results_b = None

    # ── Run A: ADV > $20M ────────────────────────────────────────────────────
    if args.run in ("a", "both"):
        out_a = _root / "results" / "v1_unbiased_20m"
        results_a = run_backtest(
            label            = "Run A — ADV > $20M  (unbiased baseline)",
            adv_m            = 20.0,
            universe         = universe,
            panel            = panel,
            indicators       = indicators,
            strategy_tickers = strategy_tickers,
            output_dir       = out_a,
            start            = args.start,
            end              = args.end,
            initial_capital  = args.initial_capital,
        )
        _p_a = replace(BASE_PARAMS, min_adv_m=20.0)
        (out_a / "strategy_meta.json").write_text(json.dumps({
            "id": "v1_unbiased_20m", "version": "1.0-unbiased-20m",
            "display_name": "Strategy 1.0 (Tiingo, ADV>$20M, ≥1yr)",
            "backtest_start": args.start, "backtest_end": args.end,
            "initial_capital": args.initial_capital,
            "params_anchor": {k: getattr(_p_a, k)
                              for k in vars(StrategyParams()) if not k.startswith("_")},
        }, ensure_ascii=False, indent=2))

    # ── Run B: ADV > $50M ────────────────────────────────────────────────────
    if args.run in ("b", "both"):
        out_b = _root / "results" / "v1_unbiased_50m"
        results_b = run_backtest(
            label            = "Run B — ADV > $50M  (sensitivity check)",
            adv_m            = 50.0,
            universe         = universe,   # same 2,943 loaded; engine applies $50M daily
            panel            = panel,
            indicators       = indicators,
            strategy_tickers = strategy_tickers,
            output_dir       = out_b,
            start            = args.start,
            end              = args.end,
            initial_capital  = args.initial_capital,
        )
        _p_b = replace(BASE_PARAMS, min_adv_m=50.0)
        (out_b / "strategy_meta.json").write_text(json.dumps({
            "id": "v1_unbiased_50m", "version": "1.0-unbiased-50m",
            "display_name": "Strategy 1.0 (Tiingo, ADV>$50M, ≥1yr)",
            "backtest_start": args.start, "backtest_end": args.end,
            "initial_capital": args.initial_capital,
            "params_anchor": {k: getattr(_p_b, k)
                              for k in vars(StrategyParams()) if not k.startswith("_")},
        }, ensure_ascii=False, indent=2))

    # ── Compare ───────────────────────────────────────────────────────────────
    if results_a and results_b:
        print(f"\n{'='*70}")
        print(f"  对比：ADV > $20M（2,943 标的）vs  ADV > $50M（同底池，引擎过滤）")
        print(f"  策略1.0，Tiingo 动态标的池（≥1年满足条件），相同策略参数")
        print(f"{'='*70}")
        print(f"  {'指标':<22} {'ADV>$20M':>14} {'ADV>$50M':>14} {'差异':>12}")
        print(f"  {'-'*64}")

        rows = [
            ("CAGR",          results_a["cagr"],             results_b["cagr"],             ".2%"),
            ("Sharpe",        results_a["sharpe"],           results_b["sharpe"],           ".3f"),
            ("Sortino",       results_a["sortino"],          results_b["sortino"],          ".3f"),
            ("最大回撤",       results_a["max_drawdown"],     results_b["max_drawdown"],     ".2%"),
            ("年化波动率",     results_a["annual_vol"],       results_b["annual_vol"],       ".2%"),
            ("胜率",           results_a["win_rate"],         results_b["win_rate"],         ".1%"),
            ("Profit Factor",  results_a["profit_factor"],   results_b["profit_factor"],    ".3f"),
            ("总交易笔数",     results_a["n_trades"],         results_b["n_trades"],         ".0f"),
            ("平均持仓天数",   results_a["avg_holding_days"], results_b["avg_holding_days"], ".1f"),
        ]
        for label, va, vb, fmt in rows:
            delta = vb - va
            sign  = "+" if delta >= 0 else ""
            print(f"  {label:<22} {va:>{14}{fmt}} {vb:>{14}{fmt}} {sign}{delta:{fmt}}")

        # Verdict
        cagr_diff = abs(results_b["cagr"] - results_a["cagr"]) * 100
        dd_diff   = abs(abs(results_b["max_drawdown"]) - abs(results_a["max_drawdown"])) * 100
        print(f"\n  CAGR 差异 = {cagr_diff:.2f}pp  |  MaxDD 差异 = {dd_diff:.2f}pp")
        if cagr_diff < 1.0 and dd_diff < 2.0:
            print("  ✓ 差异 < 阈值 → ADV 门槛对结果影响极小，当前 $20M 方案已足够")
        else:
            print("  ⚠ 差异 > 阈值 → 建议将 ADV 门槛提高至 $50M 以减少小票暴露")
        print(f"{'='*70}\n")

        # Save comparison JSON
        cmp = {
            "adv_20m": results_a,
            "adv_50m": results_b,
            "cagr_diff_pp":   round(cagr_diff, 4),
            "maxdd_diff_pp":  round(dd_diff, 4),
            "verdict":        "no_change_needed" if cagr_diff < 1.0 else "raise_adv_threshold",
        }
        (_root / "results" / "v1_unbiased_comparison.json").write_text(
            json.dumps(cmp, ensure_ascii=False, indent=2)
        )
        print("  对比结果已保存 → results/v1_unbiased_comparison.json")

    print(f"\n✓ 全部完成。总耗时 {time.time()-t_total:.1f}s\n")


if __name__ == "__main__":
    main()
